TigerStoneV/internshipProject

- internshipproject/src/pages/Join/SignIn.tsx
- internshipproject/src/pages/Join/SignUp.tsx
> Modify:  add login page

- internshipproject/src/Router.js
- internshipproject/src/components/Nav/Nav.tsx
> [ADD] nav layout

- internshipproject/src/components/Nav/Nav.tsx
- internshipproject/src/pages/Main/Main.tsx
- internshipproject/src/pages/RiderLog/RiderLog.tsx
> [ADD] front/ riderlog layout

- internshipproject/src/pages/Introduce/Team/Team.tsx
> [ADD] front/team layout

- internshipproject/src/components/Nav/Nav.tsx
> [Modify] front/nav 수정

- internshipproject/src/Router.js
- internshipproject/src/pages/Introduce/Contact/Team/Team.tsx
- internshipproject/src/pages/Introduce/Tech/Tech.tsx
> [ADD]front/tech layout

- db/migrations/20221117083151_update_questions_table.sql
- db/schema.sql
> questions 테이블 image_url  컬럼 추가

- db/migrations/20221117084123_update_questions_table.sql
- db/schema.sql
> Modify/migration questionsV2

- internshipproject/public/data/NewsData.json
- internshipproject/src/Router.js
- internshipproject/src/pages/Introduce/Team/Team.tsx
- internshipproject/src/pages/News/News.tsx
- internshipproject/src/pages/News/NewsPage.tsx
> [ADD] front/news layout

- internshipproject/public/data/NoticeData.json
- internshipproject/src/pages/Notice/Notice.tsx
- internshipproject/src/pages/Notice/NoticePage.tsx
> [ADD] front/notice layout

- internshipproject/.gitignore
- internshipproject/package-lock.json
- internshipproject/package.json
- internshipproject/public/index.html
- internshipproject/src/pages/Introduce/Contact/Contact.tsx
- internshipproject/src/pages/News/News.tsx
> [ADD] front/contact

- internshipproject/src/Router.js
- internshipproject/src/components/Nav/Nav.tsx
- internshipproject/src/pages/Join/SignIn.tsx
- internshipproject/src/pages/Join/SignUp.tsx
- internshipproject/src/pages/Join/User.jsx
> [ADD] front/join layout

- db/migrations/20221118020609_update_questions_table.sql
- db/migrations/20221118020734_update_news_table.sql
- db/schema.sql
> questions 테이블 image_url 컬럼 삭제후 news 테이블 image_url 컬럼 추가

- internshipproject/src/pages/Join/User.tsx
> [Modify]front/join type

- internshipproject/package-lock.json
- internshipproject/package.json
- internshipproject/src/pages/Introduce/Company/Company.tsx
- internshipproject/src/pages/Introduce/Team/Team.tsx
- internshipproject/src/pages/Introduce/Tech/Tech.tsx
- internshipproject/src/pages/Main/Main.tsx
- internshipproject/src/pages/RiderLog/RiderLog.tsx
- internshipproject/types/react-scroll-motion/index.d.ts
> [Modify]front/layout

- internshipproject/src/Router.js
- internshipproject/src/components/Nav/NavBlock.tsx
- internshipproject/src/pages/Introduce/Company/Company.tsx
- internshipproject/src/pages/Introduce/Contact/Contact.tsx
- internshipproject/src/pages/Introduce/Team/Team.tsx
- internshipproject/src/pages/Introduce/Tech/Tech.tsx
- internshipproject/src/pages/Join/SignIn.tsx
- internshipproject/src/pages/Main/Main.tsx
- internshipproject/src/pages/News/News.tsx
- internshipproject/src/pages/Notice/Notice.tsx
- internshipproject/src/pages/RiderLog/RiderLog.tsx
> [modify]front/nav layout

- internshipproject/package-lock.json
- internshipproject/package.json
- internshipproject/src/pages/Join/GoogleButton.jsx
- internshipproject/src/pages/Join/SignIn.tsx
- internshipproject/src/pages/Join/User.tsx
> modify: 로그인 구현

- controllers/postController.js
- models/postDao.js
- routes/postRouter.js
- services/postService.js
- utils/viewCount.js
> CRUD HOTFIX

- db/migrations/20221129062328_alter_riders_table.sql
회원가입/로그인 로직 관련 riders 테이블 migration 업데이트
: user_id 컬럼 UNIQUE 설정
> [MODIFY] migration 업데이트: riders 테이블 user_id UNIQUE 설정

- db/migrations/20221202001542_alter_users_table.sql
회원가입/로그인 로직 관련 users 테이블 migration 업데이트
: google_id 컬럼 BIGINT -> VARCHAR(500)으로 자료형 수정
> [modify] migration 업데이트:riders 테이블 google_id 자료형 변경

- db/migrations/20221202092125_alter_users_table.sql
회원가입/로그인 로직 관련 users 테이블 migration 업데이트
: google_id 컬럼 VARCHAR(500) -> BIGINT으로 자료형 재변경
> [MODIFY] migration 업데이트: users 테이블 google_id 자료형 VARCHAR > BIGINT로 변경

- db/migrations/20221204104922_alter_users_table.sql
회원가입/로그인 로직 관련 users 테이블 migration 업데이트
: google_id 컬럼 BIGINT -> VARCHAR(500)으로 자료형 수정
> [MODIFY] migration 업데이트:googleId BIGINT>VARCHAR(500)

- controllers/userController.js
- models/userDao.js
- services/userService.js
- kakaoUserInfo 반환 형태 수정
- getRiderByuser[...] 함수명 camelCase 컨벤션으로 수정 : getRiderByUser[...]
> [HOTFIX] kakaoId 수정+camelCase 컨벤션

- models/userDao.js
auth.js - adminLoginRequired - userDao - admin > admins로 오타수정
> [HOTFIX] adminLoginRequired - userDao - admin > admins로 수정

- services/userService.js
- utils/auth.js
> [HOTFIX] auth JWT: userId > id

- internshipproject/public/index.html
- internshipproject/src/components/Chat/ChatBot.js
- internshipproject/src/components/Chat/chatting.css
- internshipproject/src/pages/Join/GoogleButton.tsx
- internshipproject/src/pages/Join/SignIn.tsx
- internshipproject/src/pages/Join/User.tsx
- internshipproject/src/pages/Join/UserAdmin.tsx
- internshipproject/src/pages/Join/UserClient.tsx
- internshipproject/src/pages/News/News.jsx
- internshipproject/src/pages/News/NewsPage.tsx
- internshipproject/src/pages/Notice/Notice.jsx
- internshipproject/src/pages/Questions/Questions.jsx
> [modify] front-last
